name: Show complete dependency graph to Dependabot

permissions:
  contents: write

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '30 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: adopt
          cache: maven
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@c5ad0fd6b977364190852883b46728f25a9617c3
